name: Run tests

on:
  push:
    branches: [ "main", "pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    #build acts-util-core
    - name: Checkout ACTS-Util repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/ACTS-Util
        path: actsutil

    - run: npm install
      working-directory: ./actsutil/core
    - run: npm run compile
      working-directory: ./actsutil/core
    - run: npm link
      working-directory: ./actsutil/core
    
    #build domain
    - run: npm link acts-util-core
      working-directory: ./domain
    - run: npm install
      working-directory: ./domain
    - run: npm run build
      working-directory: ./domain
    - run: npm link
      working-directory: ./domain

    #build tests
    - run: npm link acts-util-core arabdict-domain
      working-directory: ./domain-tests
    - run: npm install
      working-directory: ./domain-tests
    - run: npm run compile
      working-directory: ./domain-tests

    #run tests
    - run: npm run run
      working-directory: ./domain-tests
